name: "Sphinx: Render docs"

on: 
  push:
    branches: gh-pages
  pull_request:
    branches: gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      INPUT_DOCS-FOLDER: docs
    steps:
    - uses: actions/checkout@v4
    - name: Build HTML
      uses: civilx64/sphinx-action@master
      with:
        docs-folder: docs/
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: docs/_build/html
    - name: Deploy
      uses: actions/deploy-pages@v4
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        timeout: 600000
        error_count: 10
        reporting_interval: 5000
        artifact_name: html-docs
        preview: false
