name: "Sphinx: Render docs"

on: 
  push:
    branches: gh-pages
  pull_request:
    branches: gh-pages

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      INPUT_DOCS-FOLDER: docs
    steps:
    - uses: actions/checkout@v4
    - name: Build HTML
      uses: civilx64/sphinx-action@master
      with:
        docs-folder: docs/
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: github-pages
        path: docs/_build/html
    - name: Setup Pages
      uses: actions/configure-pages@v4
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # Upload html docs
        path: './docs/_build/html'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4